In [1]:
import numpy as np

In [2]:
marks = np.array([
    [85, 90, 78],
    [72, 88, 91],
    [90, 95, 89],
    [65, 70, 68]
])

In [3]:
print(marks.shape)

(4, 3)


In [4]:
print(marks.ndim)

2


In [5]:
print(marks.size)

12


In [6]:
print(marks[0])

[85 90 78]


In [7]:
print(marks[:,1])

[90 88 95 70]


In [8]:
print(marks[:,2])

[78 91 89 68]


In [9]:
temperatures = np.array([
    32, 35, 31, 29, 40,
    38, 36, 33, 30, 41
])

In [12]:
add = temperatures + 2
print(add)

[34 37 33 31 42 40 38 35 32 43]


In [13]:
sub = temperatures - 5
print(sub)

[27 30 26 24 35 33 31 28 25 36]


In [14]:
multi = temperatures * 1.8
print(multi)

[57.6 63.  55.8 52.2 72.  68.4 64.8 59.4 54.  73.8]
